#!/usr/bin/env ruby
require 'rbconfig'

def expand(name)
  Config.expand(Config::CONFIG[name])
end

bindir = File.dirname(%x{which ruby})
libdir = File.join(File.dirname(bindir), 'lib')

arch = expand("arch")
libname = expand("RUBY_SO_NAME")
ver = expand("ruby_version")

args = []
args << "-I#{File.join(libdir, 'ruby', ver, arch)}"
args << "-L#{libdir}"
args << "-l#{libname}"

puts args.join(' ')
