#!/usr/bin/env ruby
require 'rbconfig'

def expand(name)
  Config.expand(Config::CONFIG[name])
end

bindir = File.dirname(%x{which ruby})
libdir = File.join(File.dirname(bindir), 'lib')

ver = expand("ruby_version")
arch = expand("arch")

args = []
args << "-I#{File.join(libdir, 'ruby', ver, arch)}"
args << "-L#{libdir}"
args << expand("LIBRUBYARG")

puts args.join(' ')
