/* -*- c++ -*- */
/* Automatically generated by augidl */
/* at Fri May 30 18:58:41 GMT Daylight Time 2008 */

#ifndef AUGEXT_INTBOX_H
#define AUGEXT_INTBOX_H

#include "augabi.h"

#if defined(__cplusplus)

#include "augabipp.hpp"

namespace aug {
    template <typename T>
    struct object_traits;
}

#endif /* __cplusplus */

/**
 * @defgroup aug_intbox aug_intbox
 *
 * @ingroup Object
 *
 * @{
 */

AUG_INTERFACE(aug_intbox);

struct aug_intboxvtbl {
    AUG_VTBL(aug_intbox);
    int (*getint_)(aug_intbox*);
};

#define aug_getint(this_) \
    (this_)->vtbl_->getint_(this_)

/** @} */

#if defined(__cplusplus)
namespace aug {
    template <>
    struct object_traits<aug_intbox> {
        typedef aug_intboxvtbl vtbl;
        static const char*
        id() AUG_NOTHROW
        {
            return aug_intboxid;
        }
    };
}

namespace aug {

    typedef aug::obref<aug_intbox> intboxref;

    inline int
    getint(aug::obref<aug_intbox> this_) AUG_NOTHROW
    {
        return this_.get()->vtbl_->getint_(this_.get());
    }

    template <typename T>
    class intbox {

        aug_intbox intbox_;

        intbox(const intbox&);

        intbox&
        operator =(const intbox&);

        static void*
        cast_(aug_intbox* this_, const char* id) AUG_NOTHROW
        {
            return aug::retget(static_cast<T*>(this_->impl_)->cast_(id));
        }
        static void
        retain_(aug_intbox* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->retain_();
        }
        static void
        release_(aug_intbox* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->release_();
        }
        static int
        getint_(aug_intbox* this_) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->getint_();
        }
        static const aug_intboxvtbl*
        vtbl()
        {
            static const aug_intboxvtbl local = {
                cast_,
                retain_,
                release_,
                getint_
            };
            return &local;
        }
    public:
        explicit
        intbox(T* impl = 0)
        {
            this->intbox_.vtbl_ = this->vtbl();
            this->intbox_.impl_ = impl;
        }
        void
        reset(T* impl)
        {
            this->intbox_.impl_ = impl;
        }
        aug_intbox*
        get() AUG_NOTHROW
        {
            return &this->intbox_;
        }
        operator aug::obref<aug_intbox>() AUG_NOTHROW
        {
            return this->get();
        }
    };

    template <typename T>
    class basic_intbox {
        intbox<basic_intbox<T> > intbox_;
        T impl_;
        int refs_;
        explicit
        basic_intbox(const T& impl)
            : impl_(impl),
              refs_(1)
        {
            this->intbox_.reset(this);
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_intbox>(id))
                return aug::object_retain<aug_object>(this->intbox_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
        }
        void
        release_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete this;
        }
        int
        getint_() AUG_NOTHROW
        {
            return this->impl_.getint_();
        }
        static aug::smartob<aug_intbox>
        create(const T& impl = T())
        {
            basic_intbox* ptr(new basic_intbox(impl));
            return aug::object_attach<aug_intbox>(ptr->intbox_);
        }
    };

    template <typename T>
    class scoped_intbox {
        intbox<scoped_intbox<T> > intbox_;
        T impl_;
    public:
        explicit
        scoped_intbox(const T& impl = T())
            : impl_(impl)
        {
            this->intbox_.reset(this);
        }
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_intbox>(id))
                return aug::object_retain<aug_object>(this->intbox_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
        }
        void
        release_() AUG_NOTHROW
        {
        }
        int
        getint_() AUG_NOTHROW
        {
            return this->impl_.getint_();
        }
        aug_object*
        base() AUG_NOTHROW
        {
            return aug::obref<aug_object>(this->intbox_).get();
        }
        aug_intbox*
        get() AUG_NOTHROW
        {
            return this->intbox_.get();
        }
        operator aug::obref<aug_intbox>() AUG_NOTHROW
        {
            return this->intbox_;
        }
    };

    typedef aug::smartob<aug_intbox> intboxptr;
}
#endif /* __cplusplus */

#endif /* AUGEXT_INTBOX_H */
