/* -*- c++ -*- */
/* Automatically generated by augidl */
/* at Fri Feb 27 07:04:13 +0000 2009 */

#ifndef AUGEXT_MAR_H
#define AUGEXT_MAR_H

#include "augabi.h"

#if defined(__cplusplus)

#include "augabipp.hpp"

namespace aug {
    template <typename T>
    struct object_traits;
}

#endif /* __cplusplus */

/* Includes. */

#include "augtypes.h"

/* Interface declarations. */

AUG_INTERFACE(aug_marstore);

/* Interface definitions. */

struct aug_mar_;

/**
 * @defgroup aug_marstore aug_marstore
 *
 * @ingroup Object
 *
 * @{
 */

struct aug_marstorevtbl {
    AUG_VTBL(aug_marstore);
    aug_result (*del_)(aug_marstore*, const char*);
    struct aug_mar_* (*get_)(aug_marstore*, const char*);
    aug_result (*put_)(aug_marstore*, const char*, struct aug_mar_*);
};

#define aug_delmar(this_, initial) \
    (this_)->vtbl_->del_(this_, initial)

#define aug_getmar(this_, initial) \
    (this_)->vtbl_->get_(this_, initial)

#define aug_putmar(this_, initial, mar) \
    (this_)->vtbl_->put_(this_, initial, mar)

/** @} */

#if defined(__cplusplus)
namespace aug {
    template <>
    struct object_traits<aug_marstore> {
        typedef aug_marstorevtbl vtbl;
        static const char*
        id() AUG_NOTHROW
        {
            return aug_marstoreid;
        }
    };
}

namespace aug {

    template <typename T>
    class marstore {

        aug_marstore marstore_;

        marstore(const marstore&);

        marstore&
        operator =(const marstore&);

        static void*
        cast_(aug_marstore* this_, const char* id) AUG_NOTHROW
        {
            return aug::retget(static_cast<T*>(this_->impl_)->cast_(id));
        }
        static void
        retain_(aug_marstore* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->retain_();
        }
        static void
        release_(aug_marstore* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->release_();
        }
        static aug_result
        del_(aug_marstore* this_, const char* initial) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->delmar_(initial);
        }
        static struct aug_mar_*
        get_(aug_marstore* this_, const char* initial) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->getmar_(initial);
        }
        static aug_result
        put_(aug_marstore* this_, const char* initial, struct aug_mar_* mar) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->putmar_(initial, mar);
        }
        static const aug_marstorevtbl*
        vtbl()
        {
            static const aug_marstorevtbl local = {
                cast_,
                retain_,
                release_,
                del_,
                get_,
                put_
            };
            return &local;
        }
    public:
        explicit
        marstore(T* impl = 0)
        {
            this->marstore_.vtbl_ = this->vtbl();
            this->marstore_.impl_ = impl;
        }
        void
        reset(T* impl)
        {
            this->marstore_.impl_ = impl;
        }
        aug_marstore*
        get() AUG_NOTHROW
        {
            return &this->marstore_;
        }
        operator aug::obref<aug_marstore>() AUG_NOTHROW
        {
            return this->get();
        }
    };

    typedef aug::obref<aug_marstore> marstoreref;
    typedef aug::smartob<aug_marstore> marstoreptr;
}
#endif /* __cplusplus */

/* C++ definitions. */

#if defined(__cplusplus)
namespace aug {

    inline void
    delmar(aug::obref<aug_marstore> this_, const char* initial)
    {
        verify(this_.get()->vtbl_->del_(this_.get(), initial), this_);
    }

    inline struct aug_mar_*
    getmar(aug::obref<aug_marstore> this_, const char* initial)
    {
        return verify(this_.get()->vtbl_->get_(this_.get(), initial), this_);
    }

    inline void
    putmar(aug::obref<aug_marstore> this_, const char* initial, struct aug_mar_* mar)
    {
        verify(this_.get()->vtbl_->put_(this_.get(), initial, mar), this_);
    }

    template <typename T>
    class marstore_base {
        marstore<T> marstore_;
        int refs_;
    protected:
        ~marstore_base()
        {
            /* Always deleted via derived, so no need to be virtual. */
        }
        marstore_base()
            : refs_(1)
        {
            this->marstore_.reset(static_cast<T*>(this));
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_marstore>(id))
                return aug::object_retain<aug_object>(this->marstore_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
        }
        void
        release_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete static_cast<T*>(this);
        }
        static aug::smartob<aug_marstore>
        attach(T* ptr)
        {
            return aug::object_attach<aug_marstore>(ptr->marstore_);
        }
    };

    template <typename T>
    class scoped_marstore_base {
        marstore<T> marstore_;
    protected:
        ~scoped_marstore_base()
        {
        }
        scoped_marstore_base()
        {
            this->marstore_.reset(static_cast<T*>(this));
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_marstore>(id))
                return aug::object_retain<aug_object>(this->marstore_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
        }
        void
        release_() AUG_NOTHROW
        {
        }
        aug_object*
        base() AUG_NOTHROW
        {
            return aug::obref<aug_object>(this->marstore_).get();
        }
        aug_marstore*
        get() AUG_NOTHROW
        {
            return this->marstore_.get();
        }
        operator aug::obref<aug_marstore>() AUG_NOTHROW
        {
            return this->marstore_;
        }
    };

    template <typename T>
    class marstore_wrapper {
        marstore<marstore_wrapper<T> > marstore_;
        T impl_;
        int refs_;
        explicit
        marstore_wrapper(const T& impl)
            : impl_(impl),
              refs_(1)
        {
            this->marstore_.reset(this);
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_marstore>(id))
                return aug::object_retain<aug_object>(this->marstore_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
        }
        void
        release_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete this;
        }
        aug_result
        delmar_(const char* initial) AUG_NOTHROW
        {
            return this->impl_.delmar_(initial);
        }
        struct aug_mar_*
        getmar_(const char* initial) AUG_NOTHROW
        {
            return this->impl_.getmar_(initial);
        }
        aug_result
        putmar_(const char* initial, struct aug_mar_* mar) AUG_NOTHROW
        {
            return this->impl_.putmar_(initial, mar);
        }
        static aug::smartob<aug_marstore>
        create(const T& impl = T())
        {
            marstore_wrapper* ptr(new marstore_wrapper(impl));
            return aug::object_attach<aug_marstore>(ptr->marstore_);
        }
    };

    template <typename T>
    class scoped_marstore_wrapper {
        marstore<scoped_marstore_wrapper<T> > marstore_;
        T impl_;
    public:
        explicit
        scoped_marstore_wrapper(const T& impl = T())
            : impl_(impl)
        {
            this->marstore_.reset(this);
        }
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_marstore>(id))
                return aug::object_retain<aug_object>(this->marstore_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
        }
        void
        release_() AUG_NOTHROW
        {
        }
        aug_result
        delmar_(const char* initial) AUG_NOTHROW
        {
            return this->impl_.delmar_(initial);
        }
        struct aug_mar_*
        getmar_(const char* initial) AUG_NOTHROW
        {
            return this->impl_.getmar_(initial);
        }
        aug_result
        putmar_(const char* initial, struct aug_mar_* mar) AUG_NOTHROW
        {
            return this->impl_.putmar_(initial, mar);
        }
        aug_object*
        base() AUG_NOTHROW
        {
            return aug::obref<aug_object>(this->marstore_).get();
        }
        aug_marstore*
        get() AUG_NOTHROW
        {
            return this->marstore_.get();
        }
        operator aug::obref<aug_marstore>() AUG_NOTHROW
        {
            return this->marstore_;
        }
    };

    typedef aug::smartob<aug_marstore> marstoreptr;
}
#endif /* __cplusplus */

#endif /* AUGEXT_MAR_H */
