/* -*- c++ -*- */
/* Automatically generated by augidl */
/* at Tue Mar 30 18:59:25 +0100 2010 */

#ifndef AUGEXT_STREAM_H
#define AUGEXT_STREAM_H

#include "augabi.h"

#if defined(__cplusplus)

#include "augabipp.hpp"

namespace aug {
    template <typename T>
    struct object_traits;
}

#endif /* __cplusplus */

/* Includes. */

#include "augtypes.h"

/* Interface declarations. */

AUG_INTERFACE(aug_stream);

/* Interface definitions. */

struct iovec;

/**
 * @defgroup aug_stream aug_stream
 *
 * @ingroup Object
 *
 * @{
 */

struct aug_streamvtbl {
    AUG_VTBL(aug_stream);
    aug_result (*shutdown_)(aug_stream*);
    aug_rsize (*read_AI_)(aug_stream*, void*, size_t);
    aug_rsize (*readv_AI_)(aug_stream*, const struct iovec*, int);
    aug_rsize (*write_AI_)(aug_stream*, const void*, size_t);
    aug_rsize (*writev_AI_)(aug_stream*, const struct iovec*, int);
};

#define aug_shutdown(this_) \
    (this_)->vtbl_->shutdown_(this_)

#define aug_read_AI(this_, buf, size) \
    (this_)->vtbl_->read_AI_(this_, buf, size)

#define aug_readv_AI(this_, iov, size) \
    (this_)->vtbl_->readv_AI_(this_, iov, size)

#define aug_write_AI(this_, buf, size) \
    (this_)->vtbl_->write_AI_(this_, buf, size)

#define aug_writev_AI(this_, iov, size) \
    (this_)->vtbl_->writev_AI_(this_, iov, size)

/** @} */

#if defined(__cplusplus)
namespace aug {
    template <>
    struct object_traits<aug_stream> {
        typedef aug_streamvtbl vtbl;
        static const char*
        id() AUG_NOTHROW
        {
            return aug_streamid;
        }
    };
}

namespace aug {

    template <typename T>
    class stream {

        aug_stream stream_;

        stream(const stream&);

        stream&
        operator =(const stream&);

        static void*
        cast_(aug_stream* this_, const char* id) AUG_NOTHROW
        {
            return aug::retget(static_cast<T*>(this_->impl_)->cast_(id));
        }
        static void
        retain_(aug_stream* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->retain_();
        }
        static void
        release_(aug_stream* this_) AUG_NOTHROW
        {
            static_cast<T*>(this_->impl_)->release_();
        }
        static aug_result
        shutdown_(aug_stream* this_) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->shutdown_();
        }
        static aug_rsize
        read_AI_(aug_stream* this_, void* buf, size_t size) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->read_AI_(buf, size);
        }
        static aug_rsize
        readv_AI_(aug_stream* this_, const struct iovec* iov, int size) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->readv_AI_(iov, size);
        }
        static aug_rsize
        write_AI_(aug_stream* this_, const void* buf, size_t size) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->write_AI_(buf, size);
        }
        static aug_rsize
        writev_AI_(aug_stream* this_, const struct iovec* iov, int size) AUG_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->writev_AI_(iov, size);
        }
        static const aug_streamvtbl*
        vtbl()
        {
            static const aug_streamvtbl local = {
                cast_,
                retain_,
                release_,
                shutdown_,
                read_AI_,
                readv_AI_,
                write_AI_,
                writev_AI_
            };
            return &local;
        }
    public:
        explicit
        stream(T* impl = 0)
        {
            this->stream_.vtbl_ = this->vtbl();
            this->stream_.impl_ = impl;
        }
        void
        reset(T* impl)
        {
            this->stream_.impl_ = impl;
        }
        aug_stream*
        get() AUG_NOTHROW
        {
            return &this->stream_;
        }
        operator aug::obref<aug_stream>() AUG_NOTHROW
        {
            return this->get();
        }
    };

    typedef aug::obref<aug_stream> streamref;
    typedef aug::smartob<aug_stream> streamptr;
}
#endif /* __cplusplus */

/* C++ definitions. */

#if defined(__cplusplus)
namespace aug {

    inline aug_result
    shutdown(aug::obref<aug_stream> this_)
    {
        return verify(this_.get()->vtbl_->shutdown_(this_.get()));
    }

    inline aug_rsize
    read_AI(aug::obref<aug_stream> this_, void* buf, size_t size)
    {
        return verify(this_.get()->vtbl_->read_AI_(this_.get(), buf, size));
    }

    inline aug_rsize
    readv_AI(aug::obref<aug_stream> this_, const struct iovec* iov, int size)
    {
        return verify(this_.get()->vtbl_->readv_AI_(this_.get(), iov, size));
    }

    inline aug_rsize
    write_AI(aug::obref<aug_stream> this_, const void* buf, size_t size)
    {
        return verify(this_.get()->vtbl_->write_AI_(this_.get(), buf, size));
    }

    inline aug_rsize
    writev_AI(aug::obref<aug_stream> this_, const struct iovec* iov, int size)
    {
        return verify(this_.get()->vtbl_->writev_AI_(this_.get(), iov, size));
    }

    template <typename T>
    class stream_base {
        stream<T> stream_;
        int refs_;
    protected:
        ~stream_base()
        {
            /* Always deleted via derived, so no need to be virtual. */
        }
        stream_base()
            : refs_(1)
        {
            this->stream_.reset(static_cast<T*>(this));
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_stream>(id))
                return aug::object_retain<aug_object>(this->stream_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
        }
        void
        release_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete static_cast<T*>(this);
        }
        static aug::smartob<aug_stream>
        attach(T* ptr)
        {
            return aug::object_attach<aug_stream>(ptr->stream_);
        }
    };

    template <typename T>
    class scoped_stream_base {
        stream<T> stream_;
    protected:
        ~scoped_stream_base()
        {
        }
        scoped_stream_base()
        {
            this->stream_.reset(static_cast<T*>(this));
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_stream>(id))
                return aug::object_retain<aug_object>(this->stream_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
        }
        void
        release_() AUG_NOTHROW
        {
        }
        aug_object*
        base() AUG_NOTHROW
        {
            return aug::obref<aug_object>(this->stream_).get();
        }
        aug_stream*
        get() AUG_NOTHROW
        {
            return this->stream_.get();
        }
        operator aug::obref<aug_stream>() AUG_NOTHROW
        {
            return this->stream_;
        }
    };

    template <typename T>
    class stream_wrapper {
        stream<stream_wrapper<T> > stream_;
        T impl_;
        int refs_;
        explicit
        stream_wrapper(const T& impl)
            : impl_(impl),
              refs_(1)
        {
            this->stream_.reset(this);
        }
    public:
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_stream>(id))
                return aug::object_retain<aug_object>(this->stream_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
        }
        void
        release_() AUG_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete this;
        }
        aug_result
        shutdown_() AUG_NOTHROW
        {
            return this->impl_.shutdown_();
        }
        aug_rsize
        read_AI_(void* buf, size_t size) AUG_NOTHROW
        {
            return this->impl_.read_AI_(buf, size);
        }
        aug_rsize
        readv_AI_(const struct iovec* iov, int size) AUG_NOTHROW
        {
            return this->impl_.readv_AI_(iov, size);
        }
        aug_rsize
        write_AI_(const void* buf, size_t size) AUG_NOTHROW
        {
            return this->impl_.write_AI_(buf, size);
        }
        aug_rsize
        writev_AI_(const struct iovec* iov, int size) AUG_NOTHROW
        {
            return this->impl_.writev_AI_(iov, size);
        }
        static aug::smartob<aug_stream>
        create(const T& impl = T())
        {
            stream_wrapper* ptr(new stream_wrapper(impl));
            return aug::object_attach<aug_stream>(ptr->stream_);
        }
    };

    template <typename T>
    class scoped_stream_wrapper {
        stream<scoped_stream_wrapper<T> > stream_;
        T impl_;
    public:
        explicit
        scoped_stream_wrapper(const T& impl = T())
            : impl_(impl)
        {
            this->stream_.reset(this);
        }
        aug::smartob<aug_object>
        cast_(const char* id) AUG_NOTHROW
        {
            if (aug::equalid<aug_object>(id) || aug::equalid<aug_stream>(id))
                return aug::object_retain<aug_object>(this->stream_);
            return null;
        }
        void
        retain_() AUG_NOTHROW
        {
        }
        void
        release_() AUG_NOTHROW
        {
        }
        aug_result
        shutdown_() AUG_NOTHROW
        {
            return this->impl_.shutdown_();
        }
        aug_rsize
        read_AI_(void* buf, size_t size) AUG_NOTHROW
        {
            return this->impl_.read_AI_(buf, size);
        }
        aug_rsize
        readv_AI_(const struct iovec* iov, int size) AUG_NOTHROW
        {
            return this->impl_.readv_AI_(iov, size);
        }
        aug_rsize
        write_AI_(const void* buf, size_t size) AUG_NOTHROW
        {
            return this->impl_.write_AI_(buf, size);
        }
        aug_rsize
        writev_AI_(const struct iovec* iov, int size) AUG_NOTHROW
        {
            return this->impl_.writev_AI_(iov, size);
        }
        aug_object*
        base() AUG_NOTHROW
        {
            return aug::obref<aug_object>(this->stream_).get();
        }
        aug_stream*
        get() AUG_NOTHROW
        {
            return this->stream_.get();
        }
        operator aug::obref<aug_stream>() AUG_NOTHROW
        {
            return this->stream_;
        }
    };

    typedef aug::smartob<aug_stream> streamptr;
}
#endif /* __cplusplus */

#endif /* AUGEXT_STREAM_H */
