#!/bin/sh

# Copyright (c) 2004, 2005, 2006, 2007, 2008, 2009 Mark Aylett <mark.aylett@gmail.com>
#
# This file is part of Aug written by Mark Aylett.
#
# Aug is released under the GPL with the additional exemption that compiling,
# linking, and/or using OpenSSL is allowed.
#
# Aug is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Aug is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

REPOSITORY='https://aug.svn.sourceforge.net/svnroot/aug'
SUBDIR=aug-trunk
USER=marayl

if [ ! -d $SUBDIR ]; then

    svn co --username=$USER $REPOSITORY/trunk $SUBDIR
    cd $SUBDIR

else

    # localver=$(svn info | awk '/^Revision:/ { print $2 }')
    # remotver=$(svn info $REPOSITORY | awk '/^Revision:/ { print $2 }')

    cd $SUBDIR

    if [ $(svn update | wc -l) -eq 1 ]; then
        echo "no change"
        exit
    fi
fi

#                       m
#           m           u
#         t a           l              l
#       p o i     s     t  p        t  i
#       r o n     t  d  i  y        h  b
#       e l t     r  e  c  t  r     r  r
#       f s a  g  i  b  a  h  u  s  e  a
#       i e i  c  c  u  s  o  b  s  a  r
#       x t n  c  t  g  t  n  y  l  d  y

BUILD0="\n\nN\nY\nN\nN\nY\nY\nN\nY\nY\n\n"
BUILD1="\n\nY\nY\nN\nN\nY\nY\nN\nY\nY\n\n"
BUILD2="\n\nN\nN\nN\nN\nY\nY\nN\nY\nY\n\n"
BUILD3="\n\nN\nY\nY\nN\nY\nY\nN\nY\nY\n\n"
BUILD4="\n\nN\nY\nN\nY\nY\nY\nN\nY\nY\n\n"
BUILD5="\n\nN\nY\nN\nN\nN\nY\nN\nY\nY\n\n"
BUILD6="\n\nN\nY\nN\nN\nY\nN\nN\nY\nY\n\n"
BUILD7="\n\nN\nY\nN\nN\nY\nY\nY\nY\nY\n\n"
BUILD8="\n\nN\nY\nN\nN\nY\nY\nN\nN\nY\n\n"
BUILD9="\n\nN\nY\nN\nN\nY\nY\nN\nY\nN\n\n"

for build in BUILD0 BUILD1 BUILD2 BUILD3 BUILD4 \
    BUILD5 BUILD6 BUILD7 BUILD8 BUILD9; do

    printf $build | ./config.pl
    (sh config.sh && make clean check) >/dev/null
done

(sh configure && make distcheck) >/dev/null
