#!/bin/sh

for path in $*; do

    cyg=`basename $path | cut -d. -f1 | cut -d- -f1`
    lib=`echo $cyg | sed -e s/^cyg/lib/`

    echo "LIBRARY $cyg-1.dll" >$lib.def
    echo 'EXPORTS' >>$lib.def
    dumpbin -EXPORTS $path \
        | awk '{ if ($4 ~ /^aug/) print "\t", $4; }' >>$lib.def
    lib /DEF:$lib.def /MACHINE:X86

done
