#!/bin/sh

# Copyright (c) 2004, 2005, 2006, 2007, 2008, 2009 Mark Aylett <mark.aylett@gmail.com>
#
# This file is part of Aug written by Mark Aylett.
#
# Aug is released under the GPL with the additional exemption that compiling,
# linking, and/or using OpenSSL is allowed.
#
# Aug is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Aug is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

copt=
lopt=
win32=

while getopts cl opt
  do
  case $opt in
      c)
          copt=1
          ;;
      l)
          lopt=1
          ;;
      ?)
          echo "usage: `basename $0`: [-c] [-l]\n" >&2
          exit 1
          ;;
  esac
done

case "`uname`" in
    *CYGWIN*|*MINGW*)
        win32=1
        ;;
esac

python="`which python`"
bindir="`dirname $python`"

if [ -z "$win32" ]; then
    version="`python -c 'import sys; print sys.version[0:3]'`"
    incdir="`echo $bindir | sed -e 's/bin/include/'`/python$version"
    libdir="`echo $bindir | sed -e 's/bin/lib/'`"
else
    version="`python -c 'import sys; print "%c%c" % (sys.version[0], sys.version[2])' | tr -d '\015'`"
    incdir="`cygpath -m $bindir/include`"
    libdir="`cygpath -m $bindir/libs`"
fi

cflags="-I$incdir"
ldflags="-L$libdir -lpython$version"

if [ -n "$copt" -a -z "$lopt" ]; then
    echo $cflags
elif [ -z "$copt" -a -n "$lopt" ]; then
    echo $ldflags
else
    echo "$cflags $ldflags"
fi
