#!/bin/sh

# Copyright (c) 2004, 2005, 2006, 2007, 2008, 2009 Mark Aylett <mark.aylett@gmail.com>
#
# This file is part of Aug written by Mark Aylett.
#
# Aug is released under the GPL with the additional exemption that compiling,
# linking, and/or using OpenSSL is allowed.
#
# Aug is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Aug is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

SRCDIR=$HOME/src/aug

mkdir -p log

echo -n "building distribution..."

(cd $SRCDIR \
    && svn update \
    && ./configure --prefix=$HOME \
    && make clean dist) >log/dist.log 2>&1

if test $? -ne 0; then
    echo " [fatal]"
    tail log/dist.log
    exit 1
fi
echo " [ok]"

# alpha-linux1
# amd64-linux1
# amd64-linux2
# openpower-linux1
# ppc-osx1
# ppc-osx2
# ppc-osx3
# shell
# sparc-solaris1
# sparc-solaris2
# x86-freebsd1
# x86-linux1
# x86-linux2
# x86-netbsd1
# x86-openbsd1
# x86-solaris1

for host in amd64-linux1 sparc-solaris1 ppc-osx3; do

    echo -n "building on $host..."

    ssh $host "chmod -R +w aug-trunk && rm -fr aug-trunk && tar xzvf $SRCDIR/aug-trunk.tar.gz && (cd aug-trunk && ./configure --prefix=$HOME && make distcheck)" >log/$host.log 2>&1

    case $? in
        0)
            echo " [ok]"
            ;;
        255)
            echo " [unavail]"
            ;;
        *)
            echo " [fail]"
            tail log/$host.log
            ;;
    esac
done
