/* -*- c++ -*- */
/* Automatically generated by aubidl */
/* at Sat Dec 29 16:43:18 GMT Standard Time 2007 */

#ifndef AUG_RPCOB_H
#define AUG_RPCOB_H

#include "aub.h"

#if defined(__cplusplus)

#include "aubpp.hpp"

# if !defined(AUB_NOTHROW)
#  define AUB_NOTHROW
# endif /* !AUB_NOTHROW */

namespace aub {
    template <typename T>
    struct object_traits;
}

#endif /* __cplusplus */
#include "augob/seqob.h"

/**
 * @defgroup aug_rpcob aug_rpcob
 *
 * @ingroup Object
 *
 * @{
 */

AUB_INTERFACE(aug_rpcob);

struct aug_rpcobvtbl {
    AUB_VTBL(aug_rpcob);
    const char* (*method_)(aug_rpcob*);
    aug_seqob* (*args_)(aug_rpcob*);
};

#define aug_rpcobmethod(this_) \
    ((aug_rpcob*)this_)->vtbl_->method_(this_)

#define aug_rpcobargs(this_) \
    ((aug_rpcob*)this_)->vtbl_->args_(this_)

/** @} */

#if defined(__cplusplus)
namespace aub {
    template <>
    struct object_traits<aug_rpcob> {
        typedef aug_rpcobvtbl vtbl;
        static const char*
        id() AUB_NOTHROW
        {
            return aug_rpcobid;
        }
    };
}

namespace aug {

    typedef aub::obref<aug_rpcob> rpcobref;

    inline const char*
    rpcobmethod(aub::obref<aug_rpcob> this_) AUB_NOTHROW
    {
        return this_.get()->vtbl_->method_(this_.get());
    }

    inline aub::smartob<aug_seqob>
    rpcobargs(aub::obref<aug_rpcob> this_) AUB_NOTHROW
    {
        return aub::object_attach<aug_seqob>(this_.get()->vtbl_->args_(this_.get()));
    }

    template <typename T>
    class rpcob {

        aug_rpcob rpcob_;

        rpcob(const rpcob&);

        rpcob&
        operator =(const rpcob&);

        static void*
        cast_(aug_rpcob* this_, const char* id) AUB_NOTHROW
        {
            return aub::incget(static_cast<T*>(this_->impl_)->cast_(id));
        }
        static int
        retain_(aug_rpcob* this_) AUB_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->retain_();
        }
        static int
        release_(aug_rpcob* this_) AUB_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->release_();
        }
        static const char*
        method_(aug_rpcob* this_) AUB_NOTHROW
        {
            return static_cast<T*>(this_->impl_)->rpcobmethod_();
        }
        static aug_seqob*
        args_(aug_rpcob* this_) AUB_NOTHROW
        {
            return aub::incget(static_cast<T*>(this_->impl_)->rpcobargs_());
        }
        static const aug_rpcobvtbl*
        vtbl()
        {
            static const aug_rpcobvtbl local = {
                cast_,
                retain_,
                release_,
                method_,
                args_
            };
            return &local;
        }
    public:
        explicit
        rpcob(T* impl = 0)
        {
            this->rpcob_.vtbl_ = this->vtbl();
            this->rpcob_.impl_ = impl;
        }
        void
        reset(T* impl)
        {
            this->rpcob_.impl_ = impl;
        }
        aug_rpcob*
        get() AUB_NOTHROW
        {
            return &this->rpcob_;
        }
        operator aub::obref<aug_rpcob>() AUB_NOTHROW
        {
            return this->get();
        }
    };

    template <typename T>
    class basic_rpcob {
        rpcob<basic_rpcob<T> > rpcob_;
        T impl_;
        int refs_;
        explicit
        basic_rpcob(const T& impl)
            : impl_(impl),
              refs_(1)
        {
            this->rpcob_.reset(this);
        }
    public:
        aub::smartob<aub_object>
        cast_(const char* id) AUB_NOTHROW
        {
            if (aub::equalid<aub_object>(id) || aub::equalid<aug_rpcob>(id))
                return aub::object_retain<aub_object>(this->rpcob_);
            return null;
        }
        int
        retain_() AUB_NOTHROW
        {
            assert(0 < this->refs_);
            ++this->refs_;
            return 0;
        }
        int
        release_() AUB_NOTHROW
        {
            assert(0 < this->refs_);
            if (0 == --this->refs_)
                delete this;
            return 0;
        }
        const char*
        rpcobmethod_() AUB_NOTHROW
        {
            return this->impl_.rpcobmethod_();
        }
        aub::smartob<aug_seqob>
        rpcobargs_() AUB_NOTHROW
        {
            return this->impl_.rpcobargs_();
        }
        static aub::smartob<aug_rpcob>
        create(const T& impl = T())
        {
            basic_rpcob* ptr(new basic_rpcob(impl));
            return aub::object_attach<aug_rpcob>(ptr->rpcob_);
        }
    };

    template <typename T>
    class scoped_rpcob {
        rpcob<scoped_rpcob<T> > rpcob_;
        T impl_;
    public:
        explicit
        scoped_rpcob(const T& impl = T())
            : impl_(impl)
        {
            this->rpcob_.reset(this);
        }
        aub::smartob<aub_object>
        cast_(const char* id) AUB_NOTHROW
        {
            if (aub::equalid<aub_object>(id) || aub::equalid<aug_rpcob>(id))
                return aub::object_retain<aub_object>(this->rpcob_);
            return null;
        }
        int
        retain_() AUB_NOTHROW
        {
            return 0;
        }
        int
        release_() AUB_NOTHROW
        {
            return 0;
        }
        const char*
        rpcobmethod_() AUB_NOTHROW
        {
            return this->impl_.rpcobmethod_();
        }
        aub::smartob<aug_seqob>
        rpcobargs_() AUB_NOTHROW
        {
            return this->impl_.rpcobargs_();
        }
        aub_object*
        base() AUB_NOTHROW
        {
            return aub::obref<aub_object>(this->rpcob_).get();
        }
        aug_rpcob*
        get() AUB_NOTHROW
        {
            return this->rpcob_.get();
        }
        operator aub::obref<aug_rpcob>() AUB_NOTHROW
        {
            return this->rpcob_;
        }
    };
}
#endif /* __cplusplus */

#endif /* AUG_RPCOB_H */
